---
galaxy_info:
  author: David Chait
  description: Install and configure MinIO object storage
  company: JGS
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
  galaxy_tags:
    - minio
    - storage
    - s3
    - object-storage

dependencies: []